@startuml

ReactInstanceManager -> ReactApplication:getPackages


activate ReactInstanceManager
ReactInstanceManager -> ReactInstanceManager:createReactContext

ReactInstanceManager -> NativeModuleRegistryBuilder:processPackage
NativeModuleRegistry <-- NativeModuleRegistryBuilder:build

ReactInstanceManager <-- NativeModuleRegistry

ReactInstanceManager -> CatalystInstanceImpl:build

activate CatalystInstanceImpl

CatalystInstanceImpl -> CatalystInstanceImpl:initializeBridge

CatalystInstanceImpl -> NativeModuleRegistry:getJavaModules

NativeModuleRegistry -> JavaModuleWrapper

CatalystInstanceImpl <-- JavaModuleWrapper

deactivate CatalystInstanceImpl

deactivate ReactInstanceManager


@enduml
